"""added course tags column and fixed course_currency to notnullable

Revision ID: 0ba9b9aa6311
Revises: 4357a54d4c4d
Create Date: 2026-10-05 10:38:25.719804

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0ba9b9aa6311"
down_revision: Union[str, Sequence[str], None] = "4357a54d4c4d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course",
        sa.Column("course_tags", postgresql.ARRAY(sa.String()), nullable=False),
    )
    op.alter_column(
        "course", "course_price_currency", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "course", "course_price_currency", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("course", "course_tags")
    # ### end Alembic commands ###
