"""added gin index to course tags

Revision ID: 22a2d41c8858
Revises: 0ba9b9aa6311
Create Date: 2026-10-05 15:30:57.469356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '22a2d41c8858'
down_revision: Union[str, Sequence[str], None] = '0ba9b9aa6311'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_course_tags'), table_name='course', postgresql_using='gin')
    op.create_index('ix_course_language', 'course', ['course_language'], unique=False)
    op.create_index('ix_course_paid', 'course', ['course_paid'], unique=False)
    op.create_index('ix_course_resource_type', 'course', ['course_resource_type'], unique=False)
    op.create_index('ix_course_tags', 'course', ['course_tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_tags', table_name='course', postgresql_using='gin')
    op.drop_index('ix_course_resource_type', table_name='course')
    op.drop_index('ix_course_paid', table_name='course')
    op.drop_index('ix_course_language', table_name='course')
    op.create_index(op.f('ix_course_course_tags'), 'course', ['course_tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
