"""enabled indexing on course_media_purchase tables

Revision ID: 277880995b9a
Revises: 632bc48bc63b
Create Date: 2026-10-06 01:06:51.719173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '277880995b9a'
down_revision: Union[str, Sequence[str], None] = '632bc48bc63b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_course_teacher_id', 'course', ['teacher_id'], unique=False)
    op.create_index('ix_media_course_id', 'media', ['course_id'], unique=False)
    op.create_index('ix_purchase_course_id', 'purchase', ['course_id'], unique=False)
    op.create_index('ix_purchase_student_id', 'purchase', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_purchase_student_id', table_name='purchase')
    op.drop_index('ix_purchase_course_id', table_name='purchase')
    op.drop_index('ix_media_course_id', table_name='media')
    op.drop_index('ix_course_teacher_id', table_name='course')
    # ### end Alembic commands ###
