"""cascade update fix

Revision ID: 4357a54d4c4d
Revises: dc74fab451e0
Create Date: 2026-09-30 17:36:25.954342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '4357a54d4c4d'
down_revision: Union[str, Sequence[str], None] = 'dc74fab451e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('course_teacher_id_fkey'), 'course', type_='foreignkey')
    op.create_foreign_key(None, 'course', 'teacher', ['teacher_id'], ['phone_no'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('enrollment_student_id_fkey'), 'enrollment', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment', 'student', ['student_id'], ['phone_no'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('purchase_student_id_fkey'), 'purchase', type_='foreignkey')
    op.create_foreign_key(None, 'purchase', 'student', ['student_id'], ['phone_no'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint(op.f('review_student_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'student', ['student_id'], ['phone_no'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey') # type: ignore
    op.create_foreign_key(op.f('review_student_id_fkey'), 'review', 'student', ['student_id'], ['phone_no'], ondelete='CASCADE')
    op.drop_constraint(None, 'purchase', type_='foreignkey') # type: ignore
    op.create_foreign_key(op.f('purchase_student_id_fkey'), 'purchase', 'student', ['student_id'], ['phone_no'], ondelete='CASCADE')
    op.drop_constraint(None, 'enrollment', type_='foreignkey') # type: ignore
    op.create_foreign_key(op.f('enrollment_student_id_fkey'), 'enrollment', 'student', ['student_id'], ['phone_no'], ondelete='CASCADE')
    op.drop_constraint(None, 'course', type_='foreignkey') # type: ignore
    op.create_foreign_key(op.f('course_teacher_id_fkey'), 'course', 'teacher', ['teacher_id'], ['phone_no'], ondelete='CASCADE')
    # ### end Alembic commands ###
