"""updated ph no column length

Revision ID: 632bc48bc63b
Revises: 7d692a9304e4
Create Date: 2026-10-06 00:19:47.711397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '632bc48bc63b'
down_revision: Union[str, Sequence[str], None] = '7d692a9304e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student', 'phone_no',
               existing_type=sa.VARCHAR(length=16),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    op.alter_column('teacher', 'phone_no',
               existing_type=sa.VARCHAR(length=16),
               type_=sqlmodel.sql.sqltypes.AutoString(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teacher', 'phone_no',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('student', 'phone_no',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=10),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
