"""added search vector column with gin index for course name

Revision ID: 7d692a9304e4
Revises: 22a2d41c8858
Create Date: 2026-10-05 22:53:05.539473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d692a9304e4'
down_revision: Union[str, Sequence[str], None] = '22a2d41c8858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', course_name)", persisted=True), nullable=True))
    op.create_index('ix_course_search_vector', 'course', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_search_vector', table_name='course', postgresql_using='gin')
    op.drop_column('course', 'search_vector')
    # ### end Alembic commands ###
