"""added four new columns in course table

Revision ID: 82f45e835676
Revises: 277880995b9a
Create Date: 2026-10-07 00:22:02.139517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '82f45e835676'
down_revision: Union[str, Sequence[str], None] = '277880995b9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('total_enrollment', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('total_review', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('total_rating', sa.Integer(), nullable=True))
    op.add_column('course', sa.Column('avg_rating', sa.Integer(), nullable=True))
    op.create_index('ix_course_created_at', 'course', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_course_created_at', table_name='course')
    op.drop_column('course', 'avg_rating')
    op.drop_column('course', 'total_rating')
    op.drop_column('course', 'total_review')
    op.drop_column('course', 'total_enrollment')
    # ### end Alembic commands ###
