"""password no unique key

Revision ID: 8f9629527b95
Revises: b36f0793a58e
Create Date: 2026-09-04 00:50:46.557942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = '8f9629527b95'
down_revision: Union[str, Sequence[str], None] = 'b36f0793a58e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_hashed_password_key'), 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_hashed_password_key'), 'user', ['hashed_password'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
