"""profile pic changed

Revision ID: b36f0793a58e
Revises: d27351ea2042
Create Date: 2026-09-02 05:25:05.300931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'b36f0793a58e'
down_revision: Union[str, Sequence[str], None] = 'd27351ea2042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('profile_pic', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('student', 'profile_photo')
    op.add_column('teacher', sa.Column('profile_pic', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('teacher', 'profile_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('teacher', 'profile_pic')
    op.add_column('student', sa.Column('profile_photo', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('student', 'profile_pic')
    # ### end Alembic commands ###
