"""course resource type nullablefalse

Revision ID: dc74fab451e0
Revises: f847176d948a
Create Date: 2026-09-24 15:33:08.387330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'dc74fab451e0'
down_revision: Union[str, Sequence[str], None] = 'f847176d948a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'course_resource_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course', 'course_resource_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
