"""changed name to total comment

Revision ID: f0787d7667c2
Revises: 82f45e835676
Create Date: 2026-10-07 01:03:12.202898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes



# revision identifiers, used by Alembic.
revision: str = 'f0787d7667c2'
down_revision: Union[str, Sequence[str], None] = '82f45e835676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('total_comment', sa.Integer(), nullable=True))
    op.drop_column('course', 'total_review')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('course', sa.Column('total_review', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('course', 'total_comment')
    # ### end Alembic commands ###
